2022-08-29 12:16:23,055 ERROR: Exception on /index [GET] [in /home/gustavo/.cache/pypoetry/virtualenvs/gustavo-W69JykhD-py3.9/lib/python3.9/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/gustavo/.cache/pypoetry/virtualenvs/gustavo-W69JykhD-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/home/gustavo/.cache/pypoetry/virtualenvs/gustavo-W69JykhD-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: post.language

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gustavo/.cache/pypoetry/virtualenvs/gustavo-W69JykhD-py3.9/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/gustavo/.cache/pypoetry/virtualenvs/gustavo-W69JykhD-py3.9/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/gustavo/.cache/pypoetry/virtualenvs/gustavo-W69JykhD-py3.9/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/gustavo/.cache/pypoetry/virtualenvs/gustavo-W69JykhD-py3.9/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/gustavo/.cache/pypoetry/virtualenvs/gustavo-W69JykhD-py3.9/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/gustavo/Flask-course/app/routes.py", line 41, in index
    posts = current_user.followed_posts().paginate(
  File "/home/gustavo/.cache/pypoetry/virtualenvs/gustavo-W69JykhD-py3.9/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 534, in paginate
    items = self.limit(per_page).offset((page - 1) * per_page).all()
  File "/home/gustavo/.cache/pypoetry/virtualenvs/gustavo-W69JykhD-py3.9/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2772, in all
    return self._iter().all()
  File "/home/gustavo/.cache/pypoetry/virtualenvs/gustavo-W69JykhD-py3.9/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2907, in _iter
    result = self.session.execute(
  File "/home/gustavo/.cache/pypoetry/virtualenvs/gustavo-W69JykhD-py3.9/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1712, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/gustavo/.cache/pypoetry/virtualenvs/gustavo-W69JykhD-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/gustavo/.cache/pypoetry/virtualenvs/gustavo-W69JykhD-py3.9/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/gustavo/.cache/pypoetry/virtualenvs/gustavo-W69JykhD-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/gustavo/.cache/pypoetry/virtualenvs/gustavo-W69JykhD-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/home/gustavo/.cache/pypoetry/virtualenvs/gustavo-W69JykhD-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/home/gustavo/.cache/pypoetry/virtualenvs/gustavo-W69JykhD-py3.9/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/gustavo/.cache/pypoetry/virtualenvs/gustavo-W69JykhD-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/home/gustavo/.cache/pypoetry/virtualenvs/gustavo-W69JykhD-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: post.language
[SQL: SELECT anon_1.post_id AS anon_1_post_id, anon_1.post_body AS anon_1_post_body, anon_1.post_timestamp AS anon_1_post_timestamp, anon_1.post_user_id AS anon_1_post_user_id, anon_1.post_language AS anon_1_post_language 
FROM (SELECT post.id AS post_id, post.body AS post_body, post.timestamp AS post_timestamp, post.user_id AS post_user_id, post.language AS post_language 
FROM post JOIN followers ON followers.followed_id = post.user_id 
WHERE followers.follower_id = ? UNION SELECT post.id AS post_id, post.body AS post_body, post.timestamp AS post_timestamp, post.user_id AS post_user_id, post.language AS post_language 
FROM post 
WHERE post.user_id = ?) AS anon_1 ORDER BY anon_1.post_timestamp DESC
 LIMIT ? OFFSET ?]
[parameters: (2, 2, 25, 0)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2022-08-29 20:57:22,301 INFO: Microblog startup [in /home/gustavo/Flask-course/app/__init__.py:52]
2022-08-29 21:11:51,301 INFO: Microblog startup [in /home/gustavo/Flask-course/app/__init__.py:52]
2022-08-29 21:12:11,818 INFO: Microblog startup [in /home/gustavo/Flask-course/app/__init__.py:52]
2022-08-29 21:12:30,131 INFO: Microblog startup [in /home/gustavo/Flask-course/app/__init__.py:52]
2022-08-29 21:12:41,166 INFO: Microblog startup [in /home/gustavo/Flask-course/app/__init__.py:52]
